version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TracepharmAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17h7ynuw60gze"
s3_prefix = "TracepharmAPI"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
